= Проект Study Center: больше взаимопомощи на учебных программах

== Идея Study Center

Одна из главных ценностей хороших образовательных программ – возможность вместе учиться с очень мотивированными и интересными людьми. Однако в действительности оказывается, что общения существенно меньше, чем могло бы быть. Студенты стесняются просить друг у друга помощи или предлагать её, долго разговаривать с преподавателями на интересующие их темы. Особенно сильно это проявляется на вечерних курсах, где вокруг каждый раз разные незнакомые люди, или в условиях удалёнки. Проект Study Center помогает преодолеть социальную дистанцию между студентами и упорядочить их общение с преподавателями.

Study Center призван помочь студентам начать общение, чтобы вместе справляться со сложностями учёбы и учиться друг у друга. Представим такую ситуацию: у абстрактного Андрея не получается домашнее задание по аппликативным функторам. Что он может сделать? Написать преподавателю? Можно, но как-то неудобно тратить личное время преподавателя, особенно если требуется подробное объяснение, а не ответ на конкретный вопрос. Написать в общий чат курса? Всем в чате прилетит уведомление с просьбой о помощи. Даже если хватит духа написать туда, не факт, что кто-то откликнется. Написать лично кому-то из студентов – сложно, если вы не знакомы. К тому же на личную просьбу сложно отказать, она во многом обязывает человека помочь.

Как же тут поможет Study Center? Основа сервиса – доска с объявлениями. Для каждого курса своя. На ней каждый студент может оставлять анонимные (или нет) сообщения трех типов: запрос о помощи, вопрос по предмету или поиск компаньона, чтобы с ним вместе поразбираться в какой-то теме. Любой человек может откликнуться на объявление, после чего открывается чат, в котором участники могут договориться о формате взаимодействия: в любимом мессенджере, видеочате или вживую. После разговора или встречи, участники отмечают затраченное время, и получатель помощи оставляет отзыв, который помогающий получит когда-нибудь потом для сохранения анонимности автора. Study Center делает всё, чтобы студентам было как можно проще психологически и физически найти кого-нибудь, кто поможет, или кому нужно помочь, а заодно и лучше разобраться в теме самому.

Идея Study Center родилась из наблюдения, какую роль в жизни студентов играет кухня в общежитии. Туда всегда можно прийти и узнать свежие новости контеста по алгоритмам, там всегда есть эксперты по всем предметам, можно попросить помощи или задать вопрос. Но не все живут в общежитии, а хочется, чтобы общение и взаимопомощь объединяли всех студентов образовательной программы. Study Center – это общажная кухня в каждый дом.

== Чем Study Center не Stackoverflow?

Пока Study Center может выглядеть просто как корпоративная версия Stackoverflow с незначительными удобствами. Но это ещё не всё. В каждом деле главное – начать, поэтому Study Center дополнительно стимулирует студентов оставлять объявления и откликаться на них. Для этого вводится простая система баллов. За пользование системой и помощь другим начисляются очки. Эти очки можно обменять на простенький, но никогда-не-лишний мерч, или на время преподавателя. А можно просто радоваться ачивкам и положению в рейтинге.

Время преподавателя? Да, имея определённое количество очков, студент или группа, скинувшись, могут договориться о дополнительном занятии по интересующей теме. Время этого занятия образовательная программа по возможности оплачивает преподавателю, или ему может быть просто самому интересно поговорить на какую-нибудь тему. Возможность такого общения с преподавателем во-первых позволяет смягчить недостатки курса, обычно возникающие из-за временнЫх ограничений, которые всегда есть (быстро пробежали сложную тему, домашка не получается). А во-вторых преподаватель вне курса часто профессионально занимается какими-то интересными вещами, о которых многим хотелось бы поговорить подробно, но времени на оффтоп обычно нет.

Поскольку любое участие и желание разобраться в теме ценно, какие-то очки начисляются за любую активность в системе. Существенно больше очков начисляется за помощь другим, потому что такая помощь позволяет не терять отстающих, а помогающему лучше разобраться в теме. Но помогать тоже нужно уметь. Очень легко ещё больше расстроить человека, у которого и так что-то не получается. Или помочь с конкретным заданием, но не с пониманием темы. Поэтому помогающим постоянно показывается soft skills подсказка о том, как действовать, чтобы и тему объяснить, и не навредить человеку (а это легко – говорить больше непонятных слов, чтобы собеседник решил, что программирование не для него). А получатель помощи после занятия выставляет помогающему оценку в терминах этой подсказки, которая влияет на очки и служит фидбеком помогающему.

Таким образом, Study Center может кратно увеличить ценность образовательных программ относительно самообучения и онлайн-курсов за счёт организации общения и взаимопомощи между сокурсниками.
